[package]
name = "arki-server"
version = "0.1.3"
authors = ["jq-rs"]

[dependencies]
tql = { git = "https://github.com/antoyo/tql", features = ["sqlite"] }
tql_macros = { git = "https://github.com/antoyo/tql" }
tokio = "0.1"
tokio-core = "0.1"
futures = "0.1"
tk-bufstream = "0.3"
netbuf = "0.3"
tk-http = "0.3"
tk-listen = "0.1"
lazy_static = "1.0"
rusqlite = "0.13"
fnv = "1.0.0"
