[package]
name = "arki-server"
version = "0.1.7"
authors = ["jq-rs"]

[dependencies]
tokio = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
futures = "0.1"
tk-bufstream = "0.3"
netbuf = "0.3"
tk-http = "0.3"
tk-listen = "0.1"
lazy_static = "1.0"
#rusqlite = "0.13"
fnv = "1.0.0"
mles-utils = "1.0.6"
bytes = "0.4"
#tql_macros = { git = "https://github.com/jq-rs/tql" }

#[dependencies.tql]
#git = "https://github.com/jq-rs/tql"
#default-features = false
#features = ["sqlite"]
