[package]
name = "mles-webproxy"
version = "0.8.2"
authors = ["jq-rs"]
edition = "2018"

description = "Mles WebProxy - an Mles WebSocket proxy and a static WWW-server based on Warp"
license = "MPL-2.0"
repository = "https://github.com/jq-rs/mles-webproxy"
documentation = "https://mles.io"
readme = "README.md"
categories = ["network-programming"]
keywords = ["websocket", "proxy", "www", "server", "mles"]

[dependencies]
tokio = "0.1"
futures = "0.1"
acme-lib = "0.7"
warp = { version = "0.1.21", features=["tls"] }
tokio-io = "0.1"
mles-utils = "1.1.0"
bytes = "0.4"
x509-parser = "0.7"
blake2 = "0.9"
aes-ctr = "0.4"
aes = "0.5"
block-modes = "0.6"
base64 = "0.12"
