[package]
name = "mles-webproxy"
version = "0.9.0"
authors = ["jq-rs"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
acme-lib = "0.8"
warp = { version = "0.2", features=["tls"] }
tokio-util = { version = "0.3", features = ["codec"] }
#mles-utils = "1.1.0"
bytes = "0.5"
x509-parser = "0.7"
blake2 = "0.9"
aes-ctr = "0.4"
aes = "0.5"
block-modes = "0.6"
base64 = "0.12"
