[package]
name = "arki-server"
version = "0.3.0"
authors = ["jq-rs"]
edition = "2018"

[dependencies]
tokio = "0.1"
futures = "0.1"
acme-lib = "0.5"
warp = { version = "0.1", features = ["tls"] }
tokio-io = "0.1"
mles-utils = "1.1.0"
bytes = "0.4"
x509-parser = "0.6"
